#!/bin/sh
set -eu
mysql --protocol=socket -uroot -p"$MYSQL_ROOT_PASSWORD" <<SQL
CREATE DATABASE IF NOT EXISTS pasarkita;
CREATE DATABASE IF NOT EXISTS warungpos;
CREATE DATABASE IF NOT EXISTS umkm_insight;
CREATE DATABASE IF NOT EXISTS supplierhub_db;
CREATE DATABASE IF NOT EXISTS logistika;
CREATE DATABASE IF NOT EXISTS tugasgateaway;
CREATE DATABASE IF NOT EXISTS wallet_db;
CREATE DATABASE IF NOT EXISTS connector_db;
CREATE USER IF NOT EXISTS 'pos_app'@'%' IDENTIFIED BY '${POS_DB_PASSWORD}';
CREATE USER IF NOT EXISTS 'marketplace_app'@'%' IDENTIFIED BY '${MARKETPLACE_DB_PASSWORD}';
CREATE USER IF NOT EXISTS 'insight_app'@'%' IDENTIFIED BY '${UMKM_DB_PASSWORD}';
CREATE USER IF NOT EXISTS 'supplierhub_app'@'%' IDENTIFIED BY '${SUPPLIERHUB_DB_PASSWORD}';
CREATE USER IF NOT EXISTS 'logistika_app'@'%' IDENTIFIED BY '${LOGISTIKA_DB_PASSWORD}';
CREATE USER IF NOT EXISTS 'integrator_app'@'%' IDENTIFIED BY '${INTEGRATOR_DB_PASSWORD}';
CREATE USER IF NOT EXISTS 'wallet_app'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
CREATE USER IF NOT EXISTS 'connector_app'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,ALTER,INDEX,DROP,REFERENCES ON warungpos.* TO 'pos_app'@'%';
GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,ALTER,INDEX,DROP,REFERENCES ON pasarkita.* TO 'marketplace_app'@'%';
GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,ALTER,INDEX,DROP,REFERENCES ON umkm_insight.* TO 'insight_app'@'%';
GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,ALTER,INDEX,DROP,REFERENCES ON supplierhub_db.* TO 'supplierhub_app'@'%';
GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,ALTER,INDEX,DROP,REFERENCES ON logistika.* TO 'logistika_app'@'%';
GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,ALTER,INDEX,DROP,REFERENCES ON tugasgateaway.* TO 'integrator_app'@'%';
GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,ALTER,INDEX,DROP,REFERENCES ON wallet_db.* TO 'wallet_app'@'%';
GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,ALTER,INDEX,DROP,REFERENCES ON connector_db.* TO 'connector_app'@'%';
FLUSH PRIVILEGES;
SQL
